spring.application.name=demo
spring.datasource.driver=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/orcl
spring.datasource.username=system
spring.datasource.password=0000


# 2. Hibernate/JPA Specifics
# Use the correct dialect for your Oracle version (e.g., Oracle12cDialect or OracleDialect for 19c/21c)
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
# spring.jpa.hibernate.ddl-auto=update

# 3. Optional: SQL Logging
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true